"""create education table

Revision ID: 9bb0d98a40ff
Revises: ff48bc9f10e2
Create Date: 2026-09-21 12:53:45.554350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb0d98a40ff'
down_revision: Union[str, Sequence[str], None] = 'ff48bc9f10e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
