"""add unique constraint to skills

Revision ID: a0a8eaa0d58b
Revises: edcd4de6d7b3
Create Date: 2026-09-23 14:16:48.925833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a8eaa0d58b'
down_revision: Union[str, Sequence[str], None] = 'edcd4de6d7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_skill', 'skills', ['name', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_skill', 'skills', type_='unique')
    # ### end Alembic commands ###
